/**
 * The configured GLaDOS World client.
 *
 * Nothing here constructs a transport or dials anything unless
 * `OMP_WORLD_SOCKET` or the hidden `world.socket` setting names an absolute
 * Unix socket.
 *
 * Everything under `./generated` is generator output copied from its
 * authoritative source, and is the only wire codec this client uses — nothing
 * here hand-rolls a protobuf encoder or a service definition. Each file keeps
 * its `@generated by` / `@generated from file` headers naming the proto it came
 * from: `llmsession*.pb.ts` from GLaDOS `sdk/llmsession/llmsession.proto`, and
 * `resource*.pb.ts` from Spacewave `bldr/resource/resource.proto`. Refresh them
 * by re-running the authoritative generator and copying the result; do not edit
 * them here.
 *
 * The `resource*.pb.ts` copies come from the vendored Spacewave tree GLaDOS
 * actually serves, not from any older snapshot: they carry
 * `supports_resource_adoption_ack`, reserve response field 3 rather than
 * decoding it as a client error, and declare `ResourceRefAdopt`.
 *
 * Two import adaptations are applied to the copies on refresh, and nothing
 * else changes. `resource_srpc.pb.ts` imports `RpcStreamPacket` from a
 * `@go/`-prefixed module path that expects a tsconfig alias; it resolves here
 * from `starpc/rpcstream/rpcstream.pb.js`, which publishes the identical
 * binding. Both `_srpc.pb.ts` files import `MessageStream` and `ProtoRpc` as
 * values; under `verbatimModuleSyntax` those are split into `import type`.
 */

export type {
	DispatchIntentLookup,
	WorldAddress,
	WorldClientOptions,
	WorldEndpoint,
	WorldRead,
	WorldService,
} from "./client.js";
export {
	assertCanonicalWorldPath,
	DEFAULT_LOOKUP_TIMEOUT_MS,
	formatWorldURI,
	formatWorldURL,
	MAX_SESSION_PAGE,
	MAX_WORLD_READ_PAGE,
	openResourceEndpoint,
	WORLD_LISTING_SELECTOR,
	WorldClient,
} from "./client.js";
export type { WorldSocketSources } from "./config.js";
export { isWorldConfigured, resolveWorldSocketPath, WORLD_SOCKET_ENV } from "./config.js";
export type {
	AgentTreeSnapshot,
	CustodySummary,
	LookupDispatchIntentResponse,
	ReadWorldURIResponse,
	SessionSummary,
} from "./generated/llmsession.pb.js";
export type { ProjectionRow, ProjectionSnapshot } from "./generated/projection.pb.js";
export type { IntentKeySource } from "./intent-key.js";
export {
	DEFAULT_DISPATCH_REPOSITORY,
	defaultCheckoutIdentity,
	defaultIntentOwnerArtifact,
	goTrimSpace,
	INTENT_KEY_PREFIX,
	intentKey,
	normalizeIntentKeySource,
	semanticWorkingDirectory,
} from "./intent-key.js";
export type { DialFn, WorldResourceRef } from "./transport.js";
export { abortError, dialUnixSocket, WorldTransport } from "./transport.js";
